In [2]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd gdrive/MyDrive/EzPC/gcn_gcn-lstm

Mounted at /content/gdrive
/content/gdrive/MyDrive/EzPC/gcn_gcn-lstm


In [1]:
!pip install stellargraph

     |████████████████████████████████| 435 kB 24.2 MB/s 
     |████████████████████████████████| 462 kB 48.6 MB/s 


In [3]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from stellargraph.core.utils import calculate_laplacian

#Run

In [4]:
def data_preparation(datafile):
    #Put the file location
    df = pd.read_csv(datafile)
    
    #type casting
    df.pm1_0 = df.pm1_0.astype(float)
    df.pm2_5 = df.pm2_5.astype(float)
    df.pm10 = df.pm10.astype(float)
    df.lat = round(round(5*df.lat.astype(float),2)/5.0,3)
    df.long= round(round(5*df.long.astype(float),2)/5.0,3)

    # Ensuring Delhi region and removing outliers from data
    df = df[(df.lat.astype(int) == 28) &(df.long.astype(int) == 77)]
    df = df[(df.pm1_0<=1500) & (df.pm2_5<=1500) & (df.pm10<=1500) & (df.pm1_0>=20) & (df.pm2_5>=30) & (df.pm10>=30)]
    #df = df[(df.humidity<=60)&(df.humidity>=7)]
    # TODO: Add buffer and consider train-data for range
    # lat_range = {'min': df.lat.min(), 'max': df.lat.max()}
    # long_range = {'min': df.long.min(), 'max': df.long.max()}
    df['lat_grid'] = df.apply(lambda row: int((n_lat_grid-1)*(row.lat-lat_range['min'])/(lat_range['max']-lat_range['min'])), axis=1 )
    df['long_grid'] = df.apply(lambda row: int((n_long_grid-1)*(row.long-long_range['min'])/(long_range['max']-long_range['min'])), axis=1 )
    df['lat_grid'] = df['lat_grid'].astype(float).astype(int)
    df['long_grid'] = df['long_grid'].astype(float).astype(int)
    means = df[["lat_grid", "long_grid", "pm2_5"]].groupby(['lat_grid', 'long_grid']).mean().reset_index()['pm2_5'].values

    # rounding @120min
    df.dateTime = pd.to_datetime(df.dateTime)
    df.dateTime = df.dateTime.dt.round('120min')
    # use time as a feature as well
    df.dateTime = df.dateTime.dt.hour*60 + df.dateTime.dt.minute

    # only PM2_5
    df = df[['dateTime','lat_grid','long_grid','pm2_5']]
    df = df.pivot_table(index=['lat_grid','long_grid'], columns='dateTime', aggfunc='mean')['pm2_5']
    df = df.fillna(0)
    df['means'] = means
    return df

In [5]:
def my_loss(y_true, y_pred):
    mse = tf.keras.losses.MeanSquaredError()
    #mask = tf.sign(y_true)
    #y_pred = y_pred*(mask)
    loss= y_true-y_pred
    #loss = mse(tf.reshape(y_true,(-1,)),tf.reshape(y_pred,(-1,)))
#     print(loss)
    return loss

In [6]:
def train_test_split(df, grid_points_indices, train_size):
    random.seed(10)
#     train_size = 0.8
    #train-data for range from total grid structure
    points_len = df.shape[0]
    test_size = int(points_len * (1-train_size))
    test_indices = random.sample(list(df.index), test_size)
    train_indices = list(set(df.index) - set(test_indices))

    train_data = df.loc[train_indices, :] 
    train_data = train_data.reindex(grid_points_indices,fill_value=0)
    train_data = np.array(train_data)

    test_data = df.loc[test_indices, :] 
    test_data = test_data.reindex(grid_points_indices,fill_value=0)
    test_data = np.array(test_data)
    return train_data, test_data

In [7]:
def scale_data(train_data, test_data):
    max_pm = train_data.max()
    min_pm = train_data.min()
    train_scaled = (train_data - min_pm) / (max_pm - min_pm)
    test_scaled = (test_data - min_pm) / (max_pm - min_pm)
    return train_scaled, test_scaled

In [8]:
def sequence_data_preparation(seq_len, train_data, test_data):
    trainX, trainY, testX, testY = [], [], [], []

    trainX.append(train_data[:, 0 : 0 + seq_len])
    trainY.append(train_data[:, -1])
    testX.append(test_data[:, 0 : 0 + seq_len])
    testY.append(test_data[:, -1])
    trainX = np.array(trainX)
    trainY = np.array(trainY)
    testX = np.array(testX)
    testY = np.array(testY)

    return trainX, trainY, testX, testY

In [9]:
def prepare_train_data(df, grid_points_indices, train_size):
    train_data, test_data = train_test_split(df, grid_points_indices, train_size)
    print("Train data: ", train_data.shape)
    print("Test data: ", test_data.shape)
    train_scaled, test_scaled = scale_data(train_data, test_data)
    trainX, trainY, testX, testY = sequence_data_preparation(
        seq_len, train_scaled, test_scaled
    )
    print(trainX.shape)
    print(trainY.shape)
    print(testX.shape)
    print(testY.shape)
    return trainX, trainY, testX, testY, train_data

In [10]:
def train_model(trainX, trainY, testX, testY, train_data):
    cb = TimingCallback()

    history = model.fit(
            trainX,
            trainY,
            epochs = 100,
            batch_size = 40,
            shuffle=True,
            verbose=0,
            validation_data=[trainX, testY],
            callbacks=[cb]
        )

    ## Rescale values
    max_pm = train_data.max()
    min_pm = train_data.min()
    train_scaled = (train_data - min_pm) / (max_pm - min_pm)
    
    print(
        "Mean Train loss: ",
        sum(tf.sqrt(history.history["loss"]))*max_pm/len(history.history["loss"]),
        "\n Last Train loss: ",
        tf.sqrt(history.history["loss"][-1])*max_pm,
        "\n Mean Test loss:",
        sum(tf.sqrt(history.history["val_loss"]))*max_pm/len(history.history["val_loss"]),
        "\n Last Test loss:",
        tf.sqrt(history.history["val_loss"][-1])*max_pm,
    #     "\nTrain time ", traintime,
        "\n Train time callbacks", sum(cb.logs)
        
    )
    sg.utils.plot_history(history)

In [11]:
def eval(model, trainX, testY):
    output = model.predict(trainX)
    # yhat = model.predict(testX)

    ## actual train and test values
    ## Rescale values
    max_pm = train_data.max()
    min_pm = train_data.min()
    print(max_pm)
    train_true = np.array((trainY * (max_pm - min_pm)) + min_pm)
    test_true = np.array((testY * (max_pm - min_pm)) + min_pm)

    ## Rescale model predicted values
    train_output = np.array((output * (max_pm - min_pm)) + min_pm)
    # test_rescpred = np.array((yhat * (max_pm - min_pm)) + min_pm)

    # # Masked predicted values
    # mask_train = tf.sign(trainY)
    mask_test = tf.sign(testY)
    # train_rescpred = train_rescpred*(mask_train)
    test_output = train_output*(mask_test)
    test_mse = my_loss(test_true, train_output)
    test_rmse = tf.sqrt(test_mse)
    print("Test RMSE: ", test_rmse)
    return test_output, test_true

In [12]:
from scipy.spatial.distance import pdist, squareform

lat_range = {'min': 28.486, 'max': 28.72}
long_range = {'min': 77.1, 'max': 77.32}
n_lat_grid = 100
n_long_grid = 100
seq_len = 12

#adjacency matrix
grid_points = pd.read_csv('grid_points.csv')
n_grid_points = grid_points.shape[0] 
X = grid_points[["lat_grid", "long_grid"]].to_numpy()
f = lambda u, v: max(abs(u-v))<=1
adj = squareform(pdist(X, f))
eye = np.identity(n_grid_points)
adj = adj+eye
print(adj.shape) 

grid_points = grid_points.pivot_table(index=['lat_grid', 'long_grid'])
grid_points_indices = grid_points.index

(1989, 1989)


In [13]:
print(adj.shape)

(1989, 1989)


#PyTorch Model
GCN layer x 2 -> LSTM layer -> Dense layer -> Sigmoid 

Define loss according to MSE 


In [71]:
class GCN_Layer(nn.Module):
    def __init__(self, input_dimensions, output_dimensions, adj):
      super().__init__()

      self.d2=input_dimensions[1]
      self.d3=input_dimensions[2]
      if(type(output_dimensions)!=type(0)):
        self.d4=output_dimensions[2]
      else:
        self.d4=output_dimensions

      self.A=torch.nn.Parameter(adj)
      #self.A=torch.nn.Parameter(torch.randn(self.d2, self.d2))
      self.kernel=torch.nn.Parameter(torch.randn(self.d3, self.d4))
      self.bias=torch.nn.Parameter(torch.randn(self.d2, 1))
      
      self.relu=torch.nn.ReLU()
      #torch.nn.init.xavier_uniform_(A, gain=1.0)
      #torch.nn.init.xavier_uniform_(kernel, gain=1.0)

    def forward(self, inputs):
      
      a=torch.permute(inputs, (0, 2, 1))
      
      neighbours=torch.matmul(a, self.A)
      
      h_graph = torch.permute(neighbours, (0, 2, 1))
      output = torch.matmul(h_graph, self.kernel)
      
      if self.bias is not None:
        output += self.bias

      output = self.relu(output)
      return output

class GCN_LSTM(nn.Module):
    def __init__(self, A, model_input_dim, batch_size=1, inp_size=1989, num_layers=1, lstm_units=4, hidden_dim=4):
      super().__init__()
      self.lstm_size=lstm_units
      self.hidden_dim=hidden_dim
      self.num_layers=num_layers
      #MANUAL
      self.initial_hidden= torch.randn(1, batch_size, hidden_dim)
      self.initial_cell= torch.randn(1, batch_size, hidden_dim)
      #Intialize the GCN_LSTM layer
      self.adj = torch.from_numpy(calculate_laplacian(A) if A is not None else None)

      adj_init = torch.zeros(inp_size, inp_size)

      if self.adj is None:
        nn.init.zeros_(adj_init)

      self.A = self.adj

      self.gcn_layer1=GCN_Layer(model_input_dim, lstm_units, self.A)
      self.gcn_layer2=GCN_Layer(torch.Size([model_input_dim[0], model_input_dim[1], lstm_units]), lstm_units, self.A)
      
      ##MANUAL
      self.lstm = nn.LSTM(input_size=inp_size, hidden_size=self.hidden_dim, num_layers=self.num_layers, dropout=0, batch_first=True)

      self.dense = torch.nn.Linear(hidden_dim, model_input_dim[1])
      self.activation = torch.nn.Sigmoid()

    def forward(self, inputs):
      output=self.gcn_layer1(inputs)
      print(f"GCN 1 --> {output.shape}")
      output=self.gcn_layer2(output)
      print('GCN 2', output.shape)
      outputgcn=torch.permute(output, [0, 2, 1])
      
      output=self.lstm(outputgcn, (self.initial_hidden, self.initial_cell))
      print(output[0].shape)
      #last hidden state
      output=torch.permute(output[0], (1, 0, 2))
      #output=output[0][0][-1]

      output=output[0]

      output=self.dense(output)
      print(output.shape)
      output=self.activation(output)
      print(output.shape)
      return output

In [72]:
inputs = torch.randn(18, 1989, 12)
labels = torch.randn(1989)

In [67]:
num=4
tanh=torch.nn.Tanh()
sigmo=torch.nn.Sigmoid()
relu_act=torch.nn.ReLU()

In [74]:
adj = adj.astype(np.float32)
model=GCN_LSTM(torch.from_numpy(adj), inputs.shape, batch_size=18, inp_size=1989)
x=model(inputs)
#print(x)
print(x.shape)

GCN 1 --> torch.Size([18, 1989, 4])
GCN 2 torch.Size([18, 1989, 4])
torch.Size([18, 4, 4])
torch.Size([18, 1989])
torch.Size([18, 1989])
torch.Size([18, 1989])


In [ ]:
model_weights=[]
for i in model.parameters():
  model_weights.append(i)

##PyTorch Equations

In [ ]:
#first layer
fixed_layers_inputs=[]
relu_outputs=[]
a=torch.squeeze(inputs)
neighbours=torch.matmul(model_weights[0], a)

fixed_layers_inputs.append(a)
h_graph = neighbours
output = torch.matmul(h_graph, model_weights[1])

fixed_layers_inputs.append(h_graph)
output += model_weights[2]
relu_outputs.append(output)
output = relu_act(output)

##second layer
a=output

neighbours=torch.matmul(model_weights[3], a)
fixed_layers_inputs.append(a)
h_graph=neighbours
output = torch.matmul(h_graph, model_weights[4])
fixed_layers_inputs.append(h_graph)
output += model_weights[5]
relu_outputs.append(output)
output = relu_act(output)

In [ ]:
y=torch.transpose(output, 1, 0)
c=model.initial_cell
h=model.initial_hidden
cache=[]
inputs_np=[]
cache.append((h, c, 0, 0, 0, 0, 0))
for i in range(4):
    inp=y[i]
    print(inp)
    inp=torch.unsqueeze(inp, 0)
    z = torch.matmul(inp, torch.transpose(model_weights[6], 0, 1))
    z += torch.matmul(torch.squeeze(h, dim=0), torch.transpose(model_weights[7], 0 ,1))
    z += model_weights[8] + model_weights[9]
    z0, z1, z2, z3 = torch.split(z, 4, dim=1)

    sig=torch.nn.Sigmoid()
    tan=torch.nn.Tanh()

    i = sig(z0)
    f = sig(z1)
    c = f * c + i * tan(z2)
    o = sig(z3)
    h = o * tan(c)

    cache.append((h, c, i, f, tan(z2), o, inp))
    
print(h)
op=torch.matmul(torch.squeeze(h, dim=1), torch.transpose(model_weights[-2], 1, 0))
op+=model_weights[-1]
print(op)

tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<SelectBackward0>)
tensor([0.0000, 0.0000, 0.4250,  ..., 0.0000, 0.0000, 0.0174],
       grad_fn=<SelectBackward0>)
tensor([0.0000, 0.0000, 1.7121,  ..., 0.0000, 0.7415, 0.8076],
       grad_fn=<SelectBackward0>)
tensor([5.6068, 4.1448, 3.0425,  ..., 4.5463, 2.2490, 2.5001],
       grad_fn=<SelectBackward0>)
tensor([[[-9.5513e-17, -2.8443e-04, -2.0654e-10, -2.0826e-01]]],
       grad_fn=<MulBackward0>)
tensor([[ 0.4213, -0.3486,  0.0150,  ...,  0.1477,  0.3030, -0.1782]],
       grad_fn=<AddBackward0>)


In [ ]:
loss=(labels-x).sum()
loss.backward()

#Backward manual equations

In [ ]:
def relu_derivative(ex):
  relu_deriv=[]
  x=ex.cpu().detach().numpy()
  for i in x:
    l=[]
    for j in i:
      if(j>0):
        l.append(1.0)
      else:
        l.append(0.0)
    relu_deriv.append(l)
  return torch.tensor(relu_deriv)

In [ ]:
#First Weights
deriv=(labels-x)
deriv=deriv*x*(1-x)
deriv=torch.unsqueeze(deriv, dim=1)
h=torch.unsqueeze(h, dim=0)

#dl_dh
dL_dh=torch.matmul(torch.transpose(deriv, 1, 0), model_weights[-2])
print(deriv)
deriv=torch.matmul(deriv, h)
print(deriv)
deriv=torch.squeeze(deriv)

tensor([[-0.4965],
        [-0.0666],
        [ 0.1386],
        ...,
        [-0.5487],
        [ 0.0674],
        [-0.4076]], grad_fn=<UnsqueezeBackward0>)
tensor([[[[[[[[ 4.7423e-17,  1.4122e-04,  1.0255e-10,  1.0340e-01],
              [ 6.3622e-18,  1.8946e-05,  1.3758e-11,  1.3872e-02],
              [-1.3236e-17, -3.9416e-05, -2.8622e-11, -2.8861e-02],
              ...,
              [ 5.2405e-17,  1.5606e-04,  1.1332e-10,  1.1427e-01],
              [-6.4408e-18, -1.9180e-05, -1.3928e-11, -1.4044e-02],
              [ 3.8929e-17,  1.1593e-04,  8.4180e-11,  8.4883e-02]]]]]]]],
       grad_fn=<CloneBackward0>)


In [ ]:
print(deriv)

tensor([[ 4.7423e-17,  1.4122e-04,  1.0255e-10,  1.0340e-01],
        [ 6.3622e-18,  1.8946e-05,  1.3758e-11,  1.3872e-02],
        [-1.3236e-17, -3.9416e-05, -2.8622e-11, -2.8861e-02],
        ...,
        [ 5.2405e-17,  1.5606e-04,  1.1332e-10,  1.1427e-01],
        [-6.4408e-18, -1.9180e-05, -1.3928e-11, -1.4044e-02],
        [ 3.8929e-17,  1.1593e-04,  8.4180e-11,  8.4883e-02]],
       grad_fn=<SqueezeBackward0>)


In [ ]:
print(dL_dh)

tensor([[-3.4949, -1.6847,  1.0154,  3.8486]], grad_fn=<MmBackward0>)


In [ ]:
dh=dL_dh
dgates=[]
dct_1=0
ft_1=0
dX=[]

for index in range(num):
  ind=num-index

  h, c, i, f, g, o, x=cache[ind]
  h=torch.squeeze(h, dim=0)
  c=torch.squeeze(c, dim=0)
  cprev=cache[ind-1][1]
  cprev=torch.squeeze(cprev, dim=0)

  dct=dh*o*(1-pow(tanh(c),2)) + dct_1*ft_1
  dct_1=dct
  ft_1=f

  dgt=dct*i*(1-pow(g,2))
  dit=dct*g*i*(1-i)
  dft=dct*cprev*f*(1-f)
  dot=dh*tanh(c)*o*(1-o)

  dgate=torch.cat((dit, dft, dgt, dot), 1)
  dXt=torch.matmul(dgate, model_weights[6])
  print(dXt)
  dX.append(dXt)
  dh=torch.matmul(dgate, model_weights[7])
  dgates.append(dgate)

dgates.reverse()
dX.reverse()

tensor([[ 4.3123e-05,  1.5761e-04,  1.5372e-04,  ..., -1.3874e-04,
          2.6247e-04,  3.0052e-04]], grad_fn=<MmBackward0>)
tensor([[ 0.0019,  0.0062,  0.0076,  ..., -0.0041, -0.0049,  0.0029]],
       grad_fn=<MmBackward0>)
tensor([[-0.0045,  0.0436,  0.0700,  ..., -0.0484, -0.0801,  0.0425]],
       grad_fn=<MmBackward0>)
tensor([[-0.0070,  0.7751,  1.1812,  ..., -0.7859, -1.2411,  0.6460]],
       grad_fn=<MmBackward0>)


In [ ]:
dW=torch.zeros((1989, num*4))
dU=torch.zeros((num, num*4))
for i in range(num):
  xnext=torch.unsqueeze(y[i], dim=1)
  hnext=torch.unsqueeze(torch.squeeze(cache[i][0]), dim=1)
  dW+=torch.matmul(xnext, dgates[i])
  dU+=torch.matmul(hnext, dgates[i])

In [ ]:
tempdX = torch.squeeze(torch.stack((dX)))
tempdX = torch.transpose(tempdX, 1, 0)
print(tempdX.shape)

torch.Size([1989, 4])


In [ ]:
#Relu derivative
#relu_deriv=[1 else 0 for i in dX if (i>0)]print(tf.transpose(tf.squeeze(dy_dx))/dgcnw11)
relu_1=relu_derivative(relu_outputs[1])
drelu_1=tempdX*relu_1

#Weight 1 derivative
temp=fixed_layers_inputs[3]
dgcnw11=torch.matmul(torch.transpose(temp, 1, 0), drelu_1)

#Input 1 Derivative
dgcn_11=torch.matmul(drelu_1, torch.transpose(model_weights[4], 1, 0))
print(dgcn_11.shape)

print()

#Weight 2 derivative
temp=fixed_layers_inputs[2]
dgcnw12=torch.matmul(dgcn_11, torch.transpose(temp, 1, 0))
print(dgcnw12.shape)

#Input 2 derivative
dgcn_12=torch.matmul(torch.transpose(dgcn_11, 1, 0), model_weights[3]) #next weight set is 0, 2
print(dgcn_12.shape)

torch.Size([1989, 4])

torch.Size([1989, 1989])
torch.Size([4, 1989])


In [ ]:
drelu_2=torch.transpose(dgcn_12, 1, 0)*relu_derivative(relu_outputs[0]) #1989, 4

#Weight 1 derivative for the second layer
temp=fixed_layers_inputs[1] #1989, 12
dgcnw_21=torch.matmul(torch.transpose(drelu_2, 1, 0), temp)
dgcnw_21=torch.transpose(dgcnw_21, 1, 0)
print(dgcnw_21.shape) #12, 4


#Input 1 derivative for the second layer 
dgcn_21=torch.matmul(drelu_2, torch.transpose(model_weights[1], 1, 0))
print(dgcn_21.shape) #1989, 12

#Weight 2 derivative for the second layer
temp=fixed_layers_inputs[0] #1989, 12
dgcnw_22=torch.matmul(temp, torch.transpose(dgcn_21, 1, 0))
print(dgcnw_22)

torch.Size([12, 4])
torch.Size([1989, 12])
tensor([[ 1.7612e-04, -5.1107e-02, -8.4432e-02,  ...,  9.0496e-02,
         -6.1686e-01, -7.4245e-01],
        [ 1.9706e-03, -1.9223e-01, -3.0729e-01,  ...,  3.4333e-01,
         -5.9058e+00, -5.0830e+00],
        [-1.0532e-03,  6.1604e-02,  9.6172e-02,  ..., -1.1097e-01,
          1.7123e+00,  1.2825e+00],
        ...,
        [ 6.6052e-04, -8.3017e-02, -1.3506e-01,  ...,  1.4767e-01,
          9.5581e-02, -7.8040e-02],
        [-1.8453e-04,  1.0037e-02,  1.6688e-02,  ..., -1.8553e-02,
          1.3776e+00,  1.2478e+00],
        [ 2.3655e-04,  7.6297e-03,  1.2437e-02,  ..., -1.2471e-02,
         -2.5207e-01, -1.9913e-01]], grad_fn=<MmBackward0>)


In [ ]:
for name, i in model.named_parameters():
  print(name, i.shape)

gcn_layer1.A torch.Size([1989, 1989])
gcn_layer1.kernel torch.Size([12, 4])
gcn_layer1.bias torch.Size([1989, 1])
gcn_layer2.A torch.Size([1989, 1989])
gcn_layer2.kernel torch.Size([4, 4])
gcn_layer2.bias torch.Size([1989, 1])
lstm.weight_ih_l0 torch.Size([16, 1989])
lstm.weight_hh_l0 torch.Size([16, 4])
lstm.bias_ih_l0 torch.Size([16])
lstm.bias_hh_l0 torch.Size([16])
dense.weight torch.Size([1989, 4])
dense.bias torch.Size([1989])


In [ ]:
print(dW)
print(dU)

tensor([[ 4.2002e-02,  2.5625e-03, -2.7445e-05,  ...,  0.0000e+00,
          1.9070e-05, -8.1627e-08],
        [ 6.9039e-02,  7.9648e-03, -3.9230e-05,  ...,  0.0000e+00,
         -7.2163e-05, -1.1577e-07],
        [ 2.6551e-04,  1.2142e-04, -8.5891e-09,  ...,  0.0000e+00,
         -2.7817e-06,  9.6925e-16],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 5.2335e-02,  3.8095e-03, -3.3230e-05,  ...,  0.0000e+00,
          6.7532e-06, -9.8685e-08],
        [ 1.4177e-01, -1.9533e-01,  7.9495e-05,  ..., -7.5101e-01,
          8.3388e-03, -5.1476e-01]], grad_fn=<AddBackward0>)
tensor([[ 2.1752e-02,  2.1911e-01, -2.1628e-04,  1.8936e-02, -2.3464e-01,
          1.3047e-03,  1.3039e-03,  1.1243e-03,  0.0000e+00,  0.0000e+00,
         -6.4159e-08,  1.3305e-03, -2.5532e-01,  7.9065e-01, -8.7830e-03,
          5.4197e-01],
        [-2.4315e-02,  2.3918e-01, -2.4166e-04, -6.8558e-03, -2.8616e-01,
          1.2923e-03,  2.

In [ ]:
print(torch.transpose(dU, 1, 0))
print(model_weights[7].grad)

tensor([[-1.0521e-04,  3.5757e-04, -5.0933e-01,  1.6984e-04],
        [ 2.8990e-05,  2.1292e-03, -2.2362e-03,  3.9164e-03],
        [-1.3714e-01,  4.1827e-01,  2.6819e-01,  3.6792e-01],
        [-2.5542e-02,  7.7738e-02,  3.0848e-02,  6.8835e-02],
        [-9.6183e-04,  2.9316e-03,  1.3674e-03,  2.5833e-03],
        [-2.1268e-02,  6.4731e-02,  5.1634e-01,  5.6335e-02],
        [-5.4274e-03,  1.6597e-02,  2.1124e-03,  1.4487e-02],
        [ 1.0582e-01, -3.1042e-01,  1.9053e-01, -2.6476e-01],
        [ 3.0333e-10, -1.0158e-09,  6.7303e-05,  6.7572e-09],
        [-2.3456e-02,  1.0979e-01, -5.6073e-01, -9.5981e-02],
        [ 8.2539e-03, -2.5150e-02,  5.3782e-01, -2.2124e-02],
        [-1.0212e-02,  3.1121e-02,  1.4517e-02,  2.7435e-02],
        [-1.3909e-04,  4.6786e-04, -7.6458e-02,  2.9455e-04],
        [-1.6056e-02,  4.8915e-02, -1.0837e+00,  4.3047e-02],
        [ 1.4641e-04, -3.9861e-03, -1.3165e+00, -3.8034e-03],
        [-2.4713e-05,  4.3555e-05,  1.8067e-04,  1.9561e-05]],
       

#Extracing weights, inputs, initial hidden states in PyTorch

In [ ]:
count=0
for name, param in model.named_parameters():
  #np_arr = i.cpu().detach().numpy()
  print(name, param.shape)
  if(len(param.shape)==2):
    f=open('pytorch_gcn/'+name+'.txt', 'w')
    values=[]
    if(count==6 or count==7 or count==10):
      print('change', name)
      param=torch.transpose(param, 1, 0)
    param=param.cpu().detach().numpy()
    for k in param:
      for l in k:
        values.append(str(l)+'\n')
    for k in values:
      f.write(k)
    f.close()
  if(len(param.shape)==1):
    f=open('pytorch_gcn/'+name+'.txt', 'w')
    values=[]
    param=param.cpu().detach().numpy()
    for k in param:
        values.append(str(k)+'\n')
    for k in values:
      f.write(k)
    f.close()
  count+=1

gcn_layer1.A torch.Size([1989, 1989])
gcn_layer1.kernel torch.Size([12, 4])
gcn_layer1.bias torch.Size([1989, 1])
gcn_layer2.A torch.Size([1989, 1989])
gcn_layer2.kernel torch.Size([4, 4])
gcn_layer2.bias torch.Size([1989, 1])
lstm.weight_ih_l0 torch.Size([16, 1989])
change lstm.weight_ih_l0
lstm.weight_hh_l0 torch.Size([16, 4])
change lstm.weight_hh_l0
lstm.bias_ih_l0 torch.Size([16])
lstm.bias_hh_l0 torch.Size([16])
dense.weight torch.Size([1989, 4])
change dense.weight
dense.bias torch.Size([1989])


In [ ]:
bias_tensor=torch.zeros([16])
for name, param in model.named_parameters():
  if('lstm.bias' in name):
    bias_tensor+=param
    #print(param)
print(bias_tensor)
f=open('pytorch_gcn/'+'lstmbias'+'.txt', 'w')
values=[]
param=bias_tensor.cpu().detach().numpy()
for k in param:
    values.append(str(k)+'\n')
for k in values:
  f.write(k)
f.close()

tensor([-0.1013, -0.4464,  0.2253,  0.7108,  0.1682,  0.3344,  0.0110,  0.2105,
        -0.2275,  0.1678, -0.8396, -0.0029, -0.0024, -0.5787, -0.0526,  0.7909],
       grad_fn=<AddBackward0>)


In [ ]:
f=open('pytorch_gcn/'+'inputs.txt', 'w')
values=[]
param=inputs.cpu().detach().numpy()
for i in param:
  for k in i:
    for j in k:
      values.append(str(j)+'\n')
for i in values:
  f.write(i)
f.close()
print(len(values))

23868


In [ ]:
other_vals=[model.initial_hidden, model.initial_cell]
for ind in range(len(other_vals)):
  if(ind==0):
    f=open('pytorch_gcn/'+'hidden.txt', 'w')
  else:
    f=open('pytorch_gcn/'+'cell.txt', 'w')
  values=[]
  param=other_vals[ind].cpu().detach().numpy()
  for i in param:
    for k in i:
      for j in k:
        values.append(str(j)+'\n')
  for i in values:
    f.write(i)
  f.close()

In [ ]:
f=open('pytorch_gcn/'+'labels.txt', 'w')
values=[]
param=labels.cpu().detach().numpy()
for i in param:
  values.append(str(i)+'\n')
for i in values:
  f.write(i)
f.close()
print(len(values))

1989


In [ ]:
from google.colab import files
files.download('pytorch_gcn/labels.txt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>